version: '3.8'

services:
  frontend:
    build:
      context: frontend/
    volumes:
      - ./frontend/:/app
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build:
      context: backend/
    volumes:
      - ./backend/:/app
    ports:
      - 3001:3000